# Aider configuration for ADD 2.0
# https://aider.chat/docs/config.html

# Model settings
model: gpt-4
edit-format: diff

# Git settings
auto-commits: false
dirty-commits: false
commit: false

# Read-only files (always include in context)
read:
  - adw.yaml
  - README.md
  - docs/journal.md
  - docs/interfaces.md

# Message template
message-template: |
  Follow Agent-Driven Development (ADD) 2.0 methodology:

  1. Read adw.yaml and docs/ before starting
  2. Follow current phase guidelines
  3. Use Conventional Commits format
  4. Update docs/journal.md with progress
  5. Respect contracts in docs/interfaces.md
  6. Commit frequently with clear messages
  7. Tag phase completions

  See full rules in .aider-rules.md

# Additional settings
show-diffs: true
pretty: true
stream: true

# Ignored patterns
ignore:
  - "*.log"
  - "node_modules/*"
  - "venv/*"
  - ".git/*"
  - "dist/*"
  - "build/*"
